import { Component, OnInit, isDevMode } from '@angular/core';
import { Router } from '@angular/router';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ILoginData } from 'src/app/interfaces/ILoginData';
import { LoginService } from 'src/app/services/auth/login.service';
import { decodeToken } from '../../core/utils/token'
import { UtilsService } from 'src/app/services/utils/utils.service';
import Swal from 'sweetalert2';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  UserDataFromToken:ILoginData;
  passwordFieldType: string = 'password';
  loginError:string = "";
  username: string = ""
  loginForm: FormGroup;
  password: string = ""
  jsonData: any[];
  AdminTokenNull: string = "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJnc2VndXJhQHNlZGFwYWwuY29tLnBlIiwiaWF0IjoxNzMzMzQ3MzY4LCJleHAiOjE3MzMzNTQ1NjgsImZpY2hhIjoiMTIzMzYiLCJub21icmVDb21wbGV0byI6IkdsYWR5cyBTZWd1cmEgUGVyYWx0YSIsImNvcnJlbyI6ImdzZWd1cmFAc2VkYXBhbC5jb20ucGUiLCJjb2RQdWVzdG8iOiIwMDAwNTE5NyIsImRlc1B1ZXN0byI6IkFuYWxpc3RhIFByaW5jaXBhbCBkZSBTaXN0ZW1hcyIsImZlY2hhIjoiMDQvMTIvMjAyNCIsImluZFJvbEFkbWluIjpudWxsLCJ1byI6IjMwMi1FVElDIiwicGVybWlzb3MiOlt7ImNhbGVuZGFyaW8iOiJDMDAyIiwidGlwbyI6IjE4MCIsImV2YWx1YWRvciI6dHJ1ZSwiZXZhbHVhZG8iOmZhbHNlLCJldmFsdWFkb3JKZWZlIjp0cnVlfSx7ImNhbGVuZGFyaW8iOiJDMDAzIiwidGlwbyI6IjkwIiwiZXZhbHVhZG9yIjp0cnVlLCJldmFsdWFkbyI6ZmFsc2UsImV2YWx1YWRvckplZmUiOnRydWV9XSwiZm90byI6Imh0dHBzOi8vd2ViYXBwMTYuc2VkYXBhbC5jb20ucGUvaW1nc2VkYXRlbC9maWNoYS8xMjMzNi5qcGcifQ.wreXC2zcrQS2LhNRjr0pmqJtbHwZz3XwK3OSak0UihhRMD9KkR2qin5GiXtq4blEiyfjN4cmO639lgwVi-xBBQ"
  AdminToken: string = "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzY2F1ZGFsZXNAc2VkYXBhbC5jb20ucGUiLCJpYXQiOjE3MjMwNTI1MjEsImV4cCI6MTcyMzA1OTcyMSwiZmljaGEiOiIxNDQ0NCIsIm5vbWJyZUNvbXBsZXRvIjoic2NhdWRhbGVzIiwiY29ycmVvIjoic2NhdWRhbGVzQHNlZGFwYWwuY29tLnBlIiwiY29kUHVlc3RvIjoiMDAwMDA0OTkiLCJkZXNQdWVzdG8iOiJKZWZlIGRlbCBFcS4gUmVtdW4uIENvbXBlbnNhIHkgQmVuZWYuIiwiZmVjaGEiOiIwNy8wOC8yMDI0IiwiaW5kUm9sQWRtaW4iOnRydWUsInBlcm1pc29zIjpbeyJjYWxlbmRhcmlvIjoiQzAwMiIsInRpcG8iOiIxODAiLCJldmFsdWFkb3IiOmZhbHNlLCJldmFsdWFkbyI6ZmFsc2V9LHsiY2FsZW5kYXJpbyI6IkMwMDMiLCJ0aXBvIjoiOTAiLCJldmFsdWFkb3IiOmZhbHNlLCJldmFsdWFkbyI6ZmFsc2V9XSwiZm90byI6Imh0dHBzOi8vd2ViYXBwMTYuc2VkYXBhbC5jb20ucGUvaW1nc2VkYXRlbC9maWNoYS8xNDQ0NC5qcGcifQ.Hx05W21JoG1TUNI4kQeSSZg7Nnm5Zug7L6Mtau944STVrY4GiXJpWyOKGl1VFwJAPSZPGfhKq4jHzwk_Xye7-Q";
  IvanAdmin: string = "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJnc2VndXJhQHNlZGFwYWwuY29tLnBlIiwiaWF0IjoxNzM0MDE0MDAzLCJleHAiOjE3MzQwMjEyMDMsImZpY2hhIjoiMTU5NjMiLCJub21icmVDb21wbGV0byI6IkdsYWR5cyBTZWd1cmEgUGVyYWx0YSIsImNvcnJlbyI6ImdzZWd1cmFAc2VkYXBhbC5jb20ucGUiLCJjb2RQdWVzdG8iOiIwMDAzNzgyMSIsImRlc1B1ZXN0byI6IkNvbnRyYXRhZG8iLCJmZWNoYSI6IjEyLzEyLzIwMjQiLCJpbmRSb2xBZG1pbiI6dHJ1ZSwidW8iOiIyMTMtRUVQIiwicGVybWlzb3MiOlt7ImNhbGVuZGFyaW8iOiJDMDAyIiwidGlwbyI6IjE4MCIsImV2YWx1YWRvciI6dHJ1ZSwiZXZhbHVhZG8iOmZhbHNlLCJldmFsdWFkb3JKZWZlIjpmYWxzZX0seyJjYWxlbmRhcmlvIjoiQzAwMyIsInRpcG8iOiI5MCIsImV2YWx1YWRvciI6dHJ1ZSwiZXZhbHVhZG8iOnRydWUsImV2YWx1YWRvckplZmUiOnRydWV9XSwiZm90byI6Imh0dHBzOi8vd2ViYXBwMTYuc2VkYXBhbC5jb20ucGUvaW1nc2VkYXRlbC9maWNoYS8xNTk2My5qcGcifQ.I5vwzDawEsMUiCTLTtuGOuxBRjWDPGIGCEh46MbOhz9USvXNMYA136C0r_GfySdbCPz6jva6c51sh8Z_YhlGJA"
  Evaluador90Jefe: string = "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJnc2VndXJhQHNlZGFwYWwuY29tLnBlIiwiaWF0IjoxNzI2NzU2Mzg1LCJleHAiOjE3MjY3NjM1ODUsImZpY2hhIjoiMTIzMzYiLCJub21icmVDb21wbGV0byI6IkdsYWR5cyBTZWd1cmEgUGVyYWx0YSIsImNvcnJlbyI6ImdzZWd1cmFAc2VkYXBhbC5jb20ucGUiLCJjb2RQdWVzdG8iOiIwMDAwNTE5NyIsImRlc1B1ZXN0byI6IkFuYWxpc3RhIFByaW5jaXBhbCBkZSBTaXN0ZW1hcyIsImZlY2hhIjoiMTkvMDkvMjAyNCIsImluZFJvbEFkbWluIjpmYWxzZSwidW8iOiIzMDItRVRJQyIsInBlcm1pc29zIjpbeyJjYWxlbmRhcmlvIjoiQzAwMiIsInRpcG8iOiIxODAiLCJldmFsdWFkb3IiOmZhbHNlLCJldmFsdWFkbyI6ZmFsc2UsImV2YWx1YWRvckplZmUiOmZhbHNlfSx7ImNhbGVuZGFyaW8iOiJDMDAzIiwidGlwbyI6IjkwIiwiZXZhbHVhZG9yIjp0cnVlLCJldmFsdWFkbyI6ZmFsc2UsImV2YWx1YWRvckplZmUiOnRydWV9XSwiZm90byI6Imh0dHBzOi8vd2ViYXBwMTYuc2VkYXBhbC5jb20ucGUvaW1nc2VkYXRlbC9maWNoYS8xMjMzNi5qcGcifQ.wo8ap8PJCWU1AdNOIhXphxypjMs9L-i-9PYNSL4O08dvLW0pVWIHJ-qfMO-4XXcf6xewgFqbSG46dv3Yv6QscA";
  Evaluador90NOJEFE: string = "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJnc2VndXJhQHNlZGFwYWwuY29tLnBlIiwiaWF0IjoxNzI2NzU2Mzg1LCJleHAiOjE3MjY3NjM1ODUsImZpY2hhIjoiMTIzMzYiLCJub21icmVDb21wbGV0byI6IkdsYWR5cyBTZWd1cmEgUGVyYWx0YSIsImNvcnJlbyI6ImdzZWd1cmFAc2VkYXBhbC5jb20ucGUiLCJjb2RQdWVzdG8iOiIwMDAwNTE5NyIsImRlc1B1ZXN0byI6IkFuYWxpc3RhIFByaW5jaXBhbCBkZSBTaXN0ZW1hcyIsImZlY2hhIjoiMTkvMDkvMjAyNCIsImluZFJvbEFkbWluIjpmYWxzZSwidW8iOiIzMDItRVRJQyIsInBlcm1pc29zIjpbeyJjYWxlbmRhcmlvIjoiQzAwMiIsInRpcG8iOiIxODAiLCJldmFsdWFkb3IiOmZhbHNlLCJldmFsdWFkbyI6ZmFsc2UsImV2YWx1YWRvckplZmUiOmZhbHNlfSx7ImNhbGVuZGFyaW8iOiJDMDAzIiwidGlwbyI6IjkwIiwiZXZhbHVhZG9yIjp0cnVlLCJldmFsdWFkbyI6ZmFsc2UsImV2YWx1YWRvckplZmUiOmZhbHNlfV0sImZvdG8iOiJodHRwczovL3dlYmFwcDE2LnNlZGFwYWwuY29tLnBlL2ltZ3NlZGF0ZWwvZmljaGEvMTIzMzYuanBnIn0.lJx9aY8Pbf328umEkkvZNjoxsPfm_1tirTko8EHZAmH8q6nxRKFMFvMgkoBGfg5Qsm7LsDzwZWwVsTiRY06Y_Q"
  Evaluador180Jefe: string = "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJnc2VndXJhQHNlZGFwYWwuY29tLnBlIiwiaWF0IjoxNzI2NzU2Mzg1LCJleHAiOjE3MjY3NjM1ODUsImZpY2hhIjoiMTIzMzYiLCJub21icmVDb21wbGV0byI6IkdsYWR5cyBTZWd1cmEgUGVyYWx0YSIsImNvcnJlbyI6ImdzZWd1cmFAc2VkYXBhbC5jb20ucGUiLCJjb2RQdWVzdG8iOiIwMDAwNTE5NyIsImRlc1B1ZXN0byI6IkFuYWxpc3RhIFByaW5jaXBhbCBkZSBTaXN0ZW1hcyIsImZlY2hhIjoiMTkvMDkvMjAyNCIsImluZFJvbEFkbWluIjpmYWxzZSwidW8iOiIzMDItRVRJQyIsInBlcm1pc29zIjpbeyJjYWxlbmRhcmlvIjoiQzAwMiIsInRpcG8iOiIxODAiLCJldmFsdWFkb3IiOnRydWUsImV2YWx1YWRvIjpmYWxzZSwiZXZhbHVhZG9ySmVmZSI6dHJ1ZX0seyJjYWxlbmRhcmlvIjoiQzAwMyIsInRpcG8iOiI5MCIsImV2YWx1YWRvciI6ZmFsc2UsImV2YWx1YWRvIjpmYWxzZSwiZXZhbHVhZG9ySmVmZSI6ZmFsc2V9XSwiZm90byI6Imh0dHBzOi8vd2ViYXBwMTYuc2VkYXBhbC5jb20ucGUvaW1nc2VkYXRlbC9maWNoYS8xMjMzNi5qcGcifQ.fvakhf55bLs-maJ-BjYqtsEWIa5SIZITxbz1AUl8XeLJYV_7b_Qf3ey9nS0h2Y_HBXUNiNP4MEkxLaqFfH-KzA"
  Evaluador180NOJEFE: string = "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJnc2VndXJhQHNlZGFwYWwuY29tLnBlIiwiaWF0IjoxNzI2NzU2Mzg1LCJleHAiOjE3MjY3NjM1ODUsImZpY2hhIjoiMTIzMzYiLCJub21icmVDb21wbGV0byI6IkdsYWR5cyBTZWd1cmEgUGVyYWx0YSIsImNvcnJlbyI6ImdzZWd1cmFAc2VkYXBhbC5jb20ucGUiLCJjb2RQdWVzdG8iOiIwMDAwNTE5NyIsImRlc1B1ZXN0byI6IkFuYWxpc3RhIFByaW5jaXBhbCBkZSBTaXN0ZW1hcyIsImZlY2hhIjoiMTkvMDkvMjAyNCIsImluZFJvbEFkbWluIjpmYWxzZSwidW8iOiIzMDItRVRJQyIsInBlcm1pc29zIjpbeyJjYWxlbmRhcmlvIjoiQzAwMiIsInRpcG8iOiIxODAiLCJldmFsdWFkb3IiOnRydWUsImV2YWx1YWRvIjpmYWxzZSwiZXZhbHVhZG9ySmVmZSI6ZmFsc2V9LHsiY2FsZW5kYXJpbyI6IkMwMDMiLCJ0aXBvIjoiOTAiLCJldmFsdWFkb3IiOmZhbHNlLCJldmFsdWFkbyI6ZmFsc2UsImV2YWx1YWRvckplZmUiOmZhbHNlfV0sImZvdG8iOiJodHRwczovL3dlYmFwcDE2LnNlZGFwYWwuY29tLnBlL2ltZ3NlZGF0ZWwvZmljaGEvMTIzMzYuanBnIn0.hGUQddM6dIxFIW5TXPgvEpnhVjpR6YpSjC8thTtuqnNDVdaMRVJJUygLMYYyBTFRmoL8U3QGQxCIWz5oButCsw"
  GladysToken2025: string = "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJnc2VndXJhQHNlZGFwYWwuY29tLnBlIiwiaWF0IjoxNzM1ODI5MDE0LCJleHAiOjE3MzU4MzYyMTQsImZpY2hhIjoiMTIzMzYiLCJub21icmVDb21wbGV0byI6IkdsYWR5cyBTZWd1cmEgUGVyYWx0YSIsImNvcnJlbyI6ImdzZWd1cmFAc2VkYXBhbC5jb20ucGUiLCJjb2RQdWVzdG8iOiIwMDAwNTE5NyIsImRlc1B1ZXN0byI6IkFuYWxpc3RhIFByaW5jaXBhbCBkZSBTaXN0ZW1hcyIsImZlY2hhIjoiMDIvMDEvMjAyNSIsImluZFJvbEFkbWluIjp0cnVlLCJ1byI6IjMwMi1FVElDIiwicGVybWlzb3MiOlt7ImNhbGVuZGFyaW8iOiJDMDA1IiwidGlwbyI6IjE4MCIsImV2YWx1YWRvciI6dHJ1ZSwiZXZhbHVhZG8iOmZhbHNlLCJldmFsdWFkb3JKZWZlIjp0cnVlfSx7ImNhbGVuZGFyaW8iOiJDMDA0IiwidGlwbyI6IjE4MCIsImV2YWx1YWRvciI6ZmFsc2UsImV2YWx1YWRvIjpmYWxzZSwiZXZhbHVhZG9ySmVmZSI6ZmFsc2V9XSwiZm90byI6Imh0dHBzOi8vd2ViYXBwMTYuc2VkYXBhbC5jb20ucGUvaW1nc2VkYXRlbC9maWNoYS8xMjMzNi5qcGcifQ.t3bOUKy9-zEpdMIlD6wZBlu0d98D8toQCJNP-VSKvSV3Verx562qQy0b8hcLX4oeaJ0uAq2BlwSdcYne-quofQ"
  Evaluado90: string = "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJyc2FudG9zQHNlZGFwYWwuY29tLnBlIiwiaWF0IjoxNzIzMDUzNTU1LCJleHAiOjE3MjMwNjA3NTUsImZpY2hhIjoiMTI4NDUiLCJub21icmVDb21wbGV0byI6IlJvbGFuZG8gU2FudG9zIE1hcnRpbmV6IiwiY29ycmVvIjoicnNhbnRvc0BzZWRhcGFsLmNvbS5wZSIsImNvZFB1ZXN0byI6IjAwMDE2NzA3IiwiZGVzUHVlc3RvIjoiQW5hbGlzdGEgUHJpbmNpcGFsIGRlIFNpc3RlbWFzIiwiZmVjaGEiOiIwNy8wOC8yMDI0IiwiaW5kUm9sQWRtaW4iOmZhbHNlLCJwZXJtaXNvcyI6W3siY2FsZW5kYXJpbyI6IkMwMDIiLCJ0aXBvIjoiMTgwIiwiZXZhbHVhZG9yIjpmYWxzZSwiZXZhbHVhZG8iOmZhbHNlfSx7ImNhbGVuZGFyaW8iOiJDMDAzIiwidGlwbyI6IjkwIiwiZXZhbHVhZG9yIjpmYWxzZSwiZXZhbHVhZG8iOnRydWV9XSwiZm90byI6Imh0dHBzOi8vd2ViYXBwMTYuc2VkYXBhbC5jb20ucGUvaW1nc2VkYXRlbC9maWNoYS8xMjg0NS5qcGcifQ.9d4l2QGB1lBY2DOGYLHBzfdxa1oPt4XJn_yM7YhrLCipQu5DHq-YFfIVauabNHwyPgWzkzLtpy3Uvf_sFYTqiw";
  Evaluado180: string = "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJyc2FudG9zQHNlZGFwYWwuY29tLnBlIiwiaWF0IjoxNzIzMDUzNTU1LCJleHAiOjE3MjMwNjA3NTUsImZpY2hhIjoiMDAwMTI4MTAiLCJub21icmVDb21wbGV0byI6IlJvbGFuZG8gU2FudG9zIE1hcnRpbmV6IiwiY29ycmVvIjoicnNhbnRvc0BzZWRhcGFsLmNvbS5wZSIsImNvZFB1ZXN0byI6IjAwMDM3NzUyIiwiZGVzUHVlc3RvIjoiQW5hbGlzdGEgUHJpbmNpcGFsIGRlIFNpc3RlbWFzIiwiZmVjaGEiOiIwNy8wOC8yMDI0IiwiaW5kUm9sQWRtaW4iOmZhbHNlLCJwZXJtaXNvcyI6W3siY2FsZW5kYXJpbyI6IkMwMDIiLCJ0aXBvIjoiMTgwIiwiZXZhbHVhZG9yIjpmYWxzZSwiZXZhbHVhZG8iOnRydWV9LHsiY2FsZW5kYXJpbyI6IkMwMDMiLCJ0aXBvIjoiOTAiLCJldmFsdWFkb3IiOmZhbHNlLCJldmFsdWFkbyI6ZmFsc2V9XSwiZm90byI6Imh0dHBzOi8vd2ViYXBwMTYuc2VkYXBhbC5jb20ucGUvaW1nc2VkYXRlbC9maWNoYS8xMjg0NS5qcGcifQ.q_0JIH-FWkUWYq11NdUz_aFp2NVl3577RHYQndVIJBhc_gII-v9QDnhrXmsLimRZJ7luhMb1TfZNZ2JeCLVp7Q"
  Token4Calenda: string = "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJyc2FudG9zQHNlZGFwYWwuY29tLnBlIiwiaWF0IjoxNzIzMDUzNTU1LCJleHAiOjE3MjMwNjA3NTUsImZpY2hhIjoiMTI4NDUiLCJub21icmVDb21wbGV0byI6IlJvbGFuZG8gU2FudG9zIE1hcnRpbmV6IiwiY29ycmVvIjoicnNhbnRvc0BzZWRhcGFsLmNvbS5wZSIsImNvZFB1ZXN0byI6IjAwMDE2NzA3IiwiZGVzUHVlc3RvIjoiQW5hbGlzdGEgUHJpbmNpcGFsIGRlIFNpc3RlbWFzIiwiZmVjaGEiOiIwNy8wOC8yMDI0IiwiaW5kUm9sQWRtaW4iOmZhbHNlLCJwZXJtaXNvcyI6W3siY2FsZW5kYXJpbyI6IkMwMDIiLCJ0aXBvIjoiMTgwIiwiZXZhbHVhZG9yIjpmYWxzZSwiZXZhbHVhZG8iOmZhbHNlLCJldmFsdWFkb3JKZWZlIjpmYWxzZX0seyJjYWxlbmRhcmlvIjoiQzAwNyIsInRpcG8iOiI5MCIsImV2YWx1YWRvciI6ZmFsc2UsImV2YWx1YWRvIjpmYWxzZSwiZXZhbHVhZG9ySmVmZSI6ZmFsc2V9LHsiY2FsZW5kYXJpbyI6IkMwMDYiLCJ0aXBvIjoiMTgwIiwiZXZhbHVhZG9yIjpmYWxzZSwiZXZhbHVhZG8iOmZhbHNlLCJldmFsdWFkb3JKZWZlIjpmYWxzZX0seyJjYWxlbmRhcmlvIjoiQzAwMyIsInRpcG8iOiI5MCIsImV2YWx1YWRvciI6ZmFsc2UsImV2YWx1YWRvIjp0cnVlLCJldmFsdWFkb3JKZWZlIjpmYWxzZX1dLCJmb3RvIjoiaHR0cHM6Ly93ZWJhcHAxNi5zZWRhcGFsLmNvbS5wZS9pbWdzZWRhdGVsL2ZpY2hhLzEyODQ1LmpwZyJ9.pqMJtrG-yp4L8cZHWHv4-xS7MPNqMqjS1yFQMwjJUGmZb4AVZklnriQSsfOHlEGMhzA3dvHXo5jzZ5wSsMr2ag";
  EVALUADO180CHICA: string = "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJyc2FudG9zQHNlZGFwYWwuY29tLnBlIiwiaWF0IjoxNzIzMDUzNTU1LCJleHAiOjE3MjMwNjA3NTUsImZpY2hhIjoiMDAwMTI4MTAiLCJub21icmVDb21wbGV0byI6IlJvbGFuZG8gU2FudG9zIE1hcnRpbmV6IiwiY29ycmVvIjoicnNhbnRvc0BzZWRhcGFsLmNvbS5wZSIsImNvZFB1ZXN0byI6IjAwMDM3NzUyIiwiZGVzUHVlc3RvIjoiQW5hbGlzdGEgUHJpbmNpcGFsIGRlIFNpc3RlbWFzIiwiZmVjaGEiOiIwNy8wOC8yMDI0IiwiaW5kUm9sQWRtaW4iOmZhbHNlLCJwZXJtaXNvcyI6W3siY2FsZW5kYXJpbyI6IkMwMDIiLCJ0aXBvIjoiMTgwIiwiZXZhbHVhZG9yIjpmYWxzZSwiZXZhbHVhZG8iOnRydWV9LHsiY2FsZW5kYXJpbyI6IkMwMDMiLCJ0aXBvIjoiOTAiLCJldmFsdWFkb3IiOmZhbHNlLCJldmFsdWFkbyI6ZmFsc2V9XSwiZm90byI6Imh0dHBzOi8vd2ViYXBwMTYuc2VkYXBhbC5jb20ucGUvaW1nc2VkYXRlbC9maWNoYS8xMjg0NS5qcGcifQ.q_0JIH-FWkUWYq11NdUz_aFp2NVl3577RHYQndVIJBhc_gII-v9QDnhrXmsLimRZJ7luhMb1TfZNZ2JeCLVp7Q"
  AdminYEvaluador: string = "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJnc2VndXJhQHNlZGFwYWwuY29tLnBlIiwiaWF0IjoxNzMyNzI2NDk3LCJleHAiOjE3MzI3MzM2OTcsImZpY2hhIjoiMTIzMzYiLCJub21icmVDb21wbGV0byI6IkdsYWR5cyBTZWd1cmEgUGVyYWx0YSIsImNvcnJlbyI6ImdzZWd1cmFAc2VkYXBhbC5jb20ucGUiLCJjb2RQdWVzdG8iOiIwMDAwNTE5NyIsImRlc1B1ZXN0byI6IkFuYWxpc3RhIFByaW5jaXBhbCBkZSBTaXN0ZW1hcyIsImZlY2hhIjoiMjcvMTEvMjAyNCIsImluZFJvbEFkbWluIjp0cnVlLCJ1byI6IjMwMi1FVElDIiwicGVybWlzb3MiOlt7ImNhbGVuZGFyaW8iOiJDMDAyIiwidGlwbyI6IjE4MCIsImV2YWx1YWRvciI6dHJ1ZSwiZXZhbHVhZG8iOmZhbHNlLCJldmFsdWFkb3JKZWZlIjp0cnVlfSx7ImNhbGVuZGFyaW8iOiJDMDA3IiwidGlwbyI6IjkwIiwiZXZhbHVhZG9yIjpmYWxzZSwiZXZhbHVhZG8iOmZhbHNlLCJldmFsdWFkb3JKZWZlIjpmYWxzZX0seyJjYWxlbmRhcmlvIjoiQzAwNiIsInRpcG8iOiIxODAiLCJldmFsdWFkb3IiOmZhbHNlLCJldmFsdWFkbyI6ZmFsc2UsImV2YWx1YWRvckplZmUiOmZhbHNlfSx7ImNhbGVuZGFyaW8iOiJDMDAzIiwidGlwbyI6IjkwIiwiZXZhbHVhZG9yIjp0cnVlLCJldmFsdWFkbyI6ZmFsc2UsImV2YWx1YWRvckplZmUiOnRydWV9XSwiZm90byI6Imh0dHBzOi8vd2ViYXBwMTYuc2VkYXBhbC5jb20ucGUvaW1nc2VkYXRlbC9maWNoYS8xMjMzNi5qcGcifQ.QjZsLMWTjrdCBTERyaA4WfdysmfFB-MZIz7sn7X8neDDOl-srQas6Qbl5o6pcgUl-CrLWG0TYkuzwTY8dGp4kw"
  EVALUADO180C001: string = "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJyc2FudG9zQHNlZGFwYWwuY29tLnBlIiwiaWF0IjoxNzIzMDUzNTU1LCJleHAiOjE3MjMwNjA3NTUsImZpY2hhIjoiMDAwMTI4MTAiLCJub21icmVDb21wbGV0byI6IlJvbGFuZG8gU2FudG9zIE1hcnRpbmV6IiwiY29ycmVvIjoicnNhbnRvc0BzZWRhcGFsLmNvbS5wZSIsImNvZFB1ZXN0byI6IjAwMDM3NzUyIiwiZGVzUHVlc3RvIjoiQW5hbGlzdGEgUHJpbmNpcGFsIGRlIFNpc3RlbWFzIiwiZmVjaGEiOiIwNy8wOC8yMDI0IiwiaW5kUm9sQWRtaW4iOmZhbHNlLCJwZXJtaXNvcyI6W3siY2FsZW5kYXJpbyI6IkMwMDEiLCJ0aXBvIjoiMTgwIiwiZXZhbHVhZG9yIjpmYWxzZSwiZXZhbHVhZG8iOnRydWV9LHsiY2FsZW5kYXJpbyI6IkMwMDIiLCJ0aXBvIjoiMTgwIiwiZXZhbHVhZG9yIjpmYWxzZSwiZXZhbHVhZG8iOmZhbHNlfSx7ImNhbGVuZGFyaW8iOiJDMDAzIiwidGlwbyI6IjkwIiwiZXZhbHVhZG9yIjpmYWxzZSwiZXZhbHVhZG8iOmZhbHNlfV0sImZvdG8iOiJodHRwczovL3dlYmFwcDE2LnNlZGFwYWwuY29tLnBlL2ltZ3NlZGF0ZWwvZmljaGEvMTI4NDUuanBnIn0.yc3kgmUbPHKmny_6vzTxaDwo7yK9YvC2NC6F1TwtjJ1zI6KmzUnhhLYIM3ziYRjX9dDPCGpX9DBIZRbcUIsWRQ"

  TestEvaluador1802: string = "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJnc2VndXJhQHNlZGFwYWwuY29tLnBlIiwiaWF0IjoxNzIzMDUyNzQwLCJleHAiOjE3MjMwNTk5NDAsImZpY2hhIjoiMDAwMTM4NTMiLCJub21icmVDb21wbGV0byI6IkdsYWR5cyBTZWd1cmEgUGVyYWx0YSIsImNvcnJlbyI6ImdzZWd1cmFAc2VkYXBhbC5jb20ucGUiLCJjb2RQdWVzdG8iOiIwMDAwNDg5NSIsImRlc1B1ZXN0byI6IkFuYWxpc3RhIFByaW5jaXBhbCBkZSBTaXN0ZW1hcyIsImZlY2hhIjoiMDcvMDgvMjAyNCIsImluZFJvbEFkbWluIjpmYWxzZSwicGVybWlzb3MiOlt7ImNhbGVuZGFyaW8iOiJDMDAyIiwidGlwbyI6IjE4MCIsImV2YWx1YWRvciI6dHJ1ZSwiZXZhbHVhZG8iOmZhbHNlfSx7ImNhbGVuZGFyaW8iOiJDMDAzIiwidGlwbyI6IjkwIiwiZXZhbHVhZG9yIjp0cnVlLCJldmFsdWFkbyI6ZmFsc2V9XSwiZm90byI6Imh0dHBzOi8vd2ViYXBwMTYuc2VkYXBhbC5jb20ucGUvaW1nc2VkYXRlbC9maWNoYS8xMjMzNi5qcGcifQ.3H4Q8rRFCOHjFRvmo7ByJh_GRMXPv8mBzxyU2vBCJYucLY1Yy673-rOWrOQfm09BwOoiEzOnML8ENTO9qzRpQQ"
  TestEvaluador1803: string = "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJnc2VndXJhQHNlZGFwYWwuY29tLnBlIiwiaWF0IjoxNzIzMDUyNzQwLCJleHAiOjE3MjMwNTk5NDAsImZpY2hhIjoiMDAwMTM4MzMiLCJub21icmVDb21wbGV0byI6IkdsYWR5cyBTZWd1cmEgUGVyYWx0YSIsImNvcnJlbyI6ImdzZWd1cmFAc2VkYXBhbC5jb20ucGUiLCJjb2RQdWVzdG8iOiIwMDAwOTgyMSIsImRlc1B1ZXN0byI6IkFuYWxpc3RhIFByaW5jaXBhbCBkZSBTaXN0ZW1hcyIsImZlY2hhIjoiMDcvMDgvMjAyNCIsImluZFJvbEFkbWluIjpmYWxzZSwicGVybWlzb3MiOlt7ImNhbGVuZGFyaW8iOiJDMDAyIiwidGlwbyI6IjE4MCIsImV2YWx1YWRvciI6dHJ1ZSwiZXZhbHVhZG8iOmZhbHNlfSx7ImNhbGVuZGFyaW8iOiJDMDAzIiwidGlwbyI6IjkwIiwiZXZhbHVhZG9yIjp0cnVlLCJldmFsdWFkbyI6ZmFsc2V9XSwiZm90byI6Imh0dHBzOi8vd2ViYXBwMTYuc2VkYXBhbC5jb20ucGUvaW1nc2VkYXRlbC9maWNoYS8xMjMzNi5qcGcifQ.r-KQ9L1g6zu0cGBQncNwrA0fFPY8hb-4bDU0UrBk4uZzBtXEXr3JgmCnMtKvRcl8gvZqpb3dD1Hy4qx6rByZBw"
  TestEvaluador1804: string = "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJnc2VndXJhQHNlZGFwYWwuY29tLnBlIiwiaWF0IjoxNzIzMDUyNzQwLCJleHAiOjE3MjMwNTk5NDAsImZpY2hhIjoiMDAwMTQzMDYiLCJub21icmVDb21wbGV0byI6IkdsYWR5cyBTZWd1cmEgUGVyYWx0YSIsImNvcnJlbyI6ImdzZWd1cmFAc2VkYXBhbC5jb20ucGUiLCJjb2RQdWVzdG8iOiIwMDAxNDc3MSIsImRlc1B1ZXN0byI6IkFuYWxpc3RhIFByaW5jaXBhbCBkZSBTaXN0ZW1hcyIsImZlY2hhIjoiMDcvMDgvMjAyNCIsImluZFJvbEFkbWluIjpmYWxzZSwicGVybWlzb3MiOlt7ImNhbGVuZGFyaW8iOiJDMDAyIiwidGlwbyI6IjE4MCIsImV2YWx1YWRvciI6dHJ1ZSwiZXZhbHVhZG8iOmZhbHNlfSx7ImNhbGVuZGFyaW8iOiJDMDAzIiwidGlwbyI6IjkwIiwiZXZhbHVhZG9yIjp0cnVlLCJldmFsdWFkbyI6ZmFsc2V9XSwiZm90byI6Imh0dHBzOi8vd2ViYXBwMTYuc2VkYXBhbC5jb20ucGUvaW1nc2VkYXRlbC9maWNoYS8xMjMzNi5qcGcifQ.XItHLSiJdNRPsP5CZB65qZ73Y0AW4-YzSFP8CdD4pmGOi3YSnIyqUwo3wYJuPc7DPku2xfDTHDQE3QXvZk-PbA"
 

  TokensinPermisos: string = "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ2ZGVsb3NzYW50b3NsQHNlZGFwYWwuY29tLnBlIiwiaWF0IjoxNzI4MDc0MzQ3LCJleHAiOjE3MjgwODE1NDcsIm5vbWJyZUNvbXBsZXRvIjoiVmljdG9yIEh1Z28gRGUgTG9zIFNhbnRvcyBMZW9uIiwiY29ycmVvIjoidmRlbG9zc2FudG9zbEBzZWRhcGFsLmNvbS5wZSIsImZlY2hhIjoiMDQvMTAvMjAyNCJ9.TmTnSWcxQu50CKnZLBlLrk8LKuLZ2tOts-RArKo7epFNfQifWE4VNY2pM1GDoIuMy18xASPxSb-LLN_K3U8W3A"
  
  constructor(private formBuilder:FormBuilder, private router:Router, private loginService:LoginService, private utilsService: UtilsService ) {  
    this.loginForm = this.formBuilder.group({
      username:['', [Validators.required]],
      password:['', Validators.required] 
    }); 
  }

  ngOnInit() {
    sessionStorage.clear();
  }


  login() {
    let username = this.loginForm.get('username') ? this.loginForm.get('username').value : '';
    let password = this.loginForm.get('password') ? this.loginForm.get('password').value : '';
      if(username != "" && password != ""){
        this.utilsService.showLoading();
        this.loginService.loginApi(username.trim(), password.trim()).subscribe({
          next: (userData) => {
            console.log('subscripte loginApi');
            
            if (isDevMode()) {
              sessionStorage.setItem('token',this.Evaluado90);
              sessionStorage.setItem('userdata', JSON.stringify(decodeToken(this.Evaluado90)));
            } else {
              sessionStorage.setItem('userdata', JSON.stringify(userData));
            }
            const AccountData: ILoginData = JSON.parse(sessionStorage.getItem('userdata')!)
            Swal.fire({
              title: 'Acceso permitido',
              text: `Bienvenido(a): ${AccountData.nombreCompleto}`,
              type: 'success',
              showCancelButton: false,
              confirmButtonText: 'Entrar'
            }).then((result) => {
              if (result.value) {
                this.router.navigateByUrl('/home');
              }else if(result.dismiss === Swal.DismissReason.close || result.dismiss === Swal.DismissReason.backdrop){
                this.router.navigate(['/home']);
              }
            });   
          },
          error: (error) => {
            console.error('Error interno',error.message);
            Swal.fire('Usuario o Contraseña invalida','Verifique los campos ingresados.', 'error');
          }
        });  
      }else{
        Swal.fire('Campos incompletos', 'Por favor, complete todos los campos obligatorios para continuar.', 'warning');
      }
    
  }
}
